### ISSUE TITLE
go-swagger

### ISSUE THREAD

**Issue by casualjim** [babelrpc/swagger2#1]
Hi

I was wondering if you had seen this project: https://github.com/go-swagger/go-swagger

I'd like to understand if there is a particular reason (other than because I felt like it) that you created this project.

the project I linked to also contains this functionality and more

**Comment by ancientlore** [comment]
This project was originally created for the [babel2swagger](https://github.com/babelrpc/babel/tree/master/cmd/babel2swagger) utility. I think it was created about a year ago, but only recently appeared on GitHub when we were given permission to open source [babelrpc](https://github.com/babelrpc). As we get going, we might consider switching to [go-swagger](https://github.com/go-swagger/go-swagger), but during the original development we didn't find a good Swagger 2.0 compliant package that met our needs (mainly manipulating the objects and serialization). If I recall, most of the packages didn't support 2.0 yet or had not been touched in a long time. I can't remember if we ran into go-swagger back then.

**Comment by casualjim** [comment]
yeah I also started the 2.0 implementation about 11 months ago.
Glad to hear there is no real show stopper in my implementation.
